services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    # Default command, can be overridden by "docker compose run" command
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"